@startuml

component 회원
component 혜택
component 주문
component 카탈로그
component 리뷰
component 결제
component 배송
component 정산

회원 -right- 혜택
주문 -up- 회원
주문 -up- 혜택
주문 -left- 카탈로그
주문 -right- 결제
리뷰 -up- 카탈로그
주문 -down- 배송
정산 -up- 주문

@enduml