@startuml

actor "사용자" as actor
participant "인증 필터" as a
participant "접근 검사 필터" as b
participant "실제 구현" as c

activate actor

actor -> a: 1: 요청
activate a
    a -> a: 1.1: 인증 상태 정보 생성
    activate a
    deactivate a
    a -> b: 1.2: 요청 전달
    activate b
alt 권한 있으면
        b -> c: 1.2.1: 요청 전달
        activate c
            c -> c: 1.2.1.1: 요청 처리
            activate c
            deactivate c
        b <-- c: 1.2.1.2: 응답
        deactivate c
    a <-- b: 1.3: 응답
    deactivate b
actor <-- a: 1.4: 응답
deactivate a
    deactivate c
else 권한 없으면
    a <-- b: 1.2: 에러 응답
        activate b
        deactivate b
    activate a
actor <-- a: 2.1: 에러 응답
    deactivate a
end
deactivate a

deactivate actor

@enduml