@startuml

rectangle "Address" as a
rectangle "Shipping\nInfo" as b
rectangle "<<루트>>\nOrder" as c
rectangle "Payment\nInfo" as d
rectangle "Delivery\nTracking" as e
rectangle "OrderLine" as f
rectangle "Receiver" as j
rectangle "Orderer" as k

a -down- b
b -down- c
c -down- d
c -left- f
f -up- e
e -right- c
c -right- k
b -right- j
j -down- k

@enduml